35/unit tests
plansoft-it/ClassManager pull request #43
Opened 2021-05-06 13:06 UTC by antoniocaia

Unit test for ClassroomService and ClassroomController

2021-05-07 13:39 UTC, Wabri requested changes
Nei metodi di test sarebbe visivamente meglio avere la spaziatura tra i diversi elementi: dichiarazione, esecuzione, assunzioni. Per esempio nel test testFindAllPage io formatterei in uesto modo:

```Java
	@Test
	public void testFindAllPage() {
		Classroom c1 = new Classroom("class1", 1);
		Classroom c2 = new Classroom("class2", 2);
		List<Classroom> classes = Arrays.asList(c1, c2);
                Page<Classroom> expectedPageClasses = new PageImpl<Classroom>(classes);
	        Pageable pageable = PageRequest.of(0, 2);
		
                when(repository.findAll(pageable)).thenReturn(new PageImpl<Classroom>(classes));
		Page<Classroom> actualPageClasses = service.findAll(pageable);

		assertEquals(expectedPageClasses, actualPageClasses);
	}
```

2021-05-07 13:39 UTC, Wabri commented on src/main/java/it/plansoft/classmanager/model/Classroom.java
> +		if (id == null) {
Perchè hai fatto un if annidato invece che un solo if?

```suggestion
		if (id == null) && (other.id != null) {
```

2021-05-07 13:39 UTC, Wabri commented on src/main/java/it/plansoft/classmanager/model/Classroom.java
> +		if (id == null) {
Come anche negli altri if che ci sono

2021-05-07 13:39 UTC, Wabri commented on src/main/java/it/plansoft/classmanager/model/Student.java
> +		if (classroom == null) {
Perchè hai fatto un if annidato invece che un solo if?

2021-05-07 13:39 UTC, Wabri commented on src/test/java/it/plansoft/classmanager/controller/ClassroomControllerTest.java
> +		List<Classroom> actualClasses = new ObjectMapper().readValue(jsonString, new TypeReference<List<Classroom>>() {}); // Slow, array is way faster
Spiega il commento e nel caso toglilo

2021-05-07 13:39 UTC, Wabri commented on src/test/java/it/plansoft/classmanager/controller/ClassroomControllerTest.java
> +		List<Classroom> actualClasses = new ObjectMapper().readValue(jsonString, new TypeReference<List<Classroom>>() {}); // Slow, array is way faster
Spiega il commento e nel caso toglilo

2021-05-07 13:39 UTC, Wabri commented on src/main/java/it/plansoft/classmanager/controller/ClassroomController.java
> +		return c.getStudents().stream()
Questo lo fai per avere sempre gli studenti in ordine? Il fatto che sono più di 2k di studenti nel db potrebbe essere un problema?

2021-05-07 13:39 UTC, Wabri commented on src/test/java/it/plansoft/classmanager/controller/ClassroomControllerTest.java
> +		List<Student> actualStudents = new ObjectMapper().readValue(jsonString, new TypeReference<List<Student>>() {}); // Slow, array is way faster
Vedi commento alla linea 81

2021-05-10 07:00 UTC, antoniocaia commented on src/main/java/it/plansoft/classmanager/model/Classroom.java
> +		if (id == null) {
Sono metodi autogenerati attraverso Eclipse, provvederò a formattarli meglio.

2021-05-10 07:10 UTC, antoniocaia commented on src/test/java/it/plansoft/classmanager/controller/ClassroomControllerTest.java
> +		List<Classroom> actualClasses = new ObjectMapper().readValue(jsonString, new TypeReference<List<Classroom>>() {}); // Slow, array is way faster
Il commento era un promemoria nel caso il test fosse risultare troppo lento. 
La soluzione più rapida prevede l'uso di array piuttosto che di liste, ma visto che è necesario confrontare liste e la procedura non impatta eccessivamente il tempo di test ho deciso di non "ottimizzare" il test.

2021-05-10 07:19 UTC, antoniocaia commented on src/main/java/it/plansoft/classmanager/controller/ClassroomController.java
> +		return c.getStudents().stream()
Sì, Classroom ha un set non ordinato di studenti, e di conseguenza nel frontend la lista di studenti di una classe viene visualizzata sempre con un ordine casuale.
Ordinare la lista non risulta eccessivamente dispendioso perchè durante l'invocazione il metodo si limita ad ordinare gli studenti di una sola classe (realisticamente non più di 30 elementi).
Una possibile alternativa ovviamente consiste nel sostituire il set in Classroom con una lista.

2021-05-10 09:49 UTC, Wabri commented on src/main/java/it/plansoft/classmanager/controller/ClassroomController.java
> +		return c.getStudents().stream()
@LORYMAX4 Che ne pensi di cambiare il set con una lista?

2021-05-10 09:49 UTC, Wabri commented on src/main/java/it/plansoft/classmanager/model/Classroom.java
> +		if (id == null) {
Quando risolvi un commento ricordati di cliccare su "Resolve conversation"

2021-05-10 09:54 UTC, LORYMAX4 commented on src/main/java/it/plansoft/classmanager/controller/ClassroomController.java
> +		return c.getStudents().stream()
Mi sembra un'ottima idea.

2021-05-11 07:24 UTC, antoniocaia commented on src/main/java/it/plansoft/classmanager/controller/ClassroomController.java
> +		return c.getStudents().stream()
Appena viene fatto il merge della issue #46 faccio il rebase e aggiorno il metodo

2021-05-11 07:35 UTC, Wabri approved these changes

2021-05-11 07:35 UTC, merged

2021-05-11 07:36 UTC, Wabri commented on src/main/java/it/plansoft/classmanager/controller/ClassroomController.java
> +		return c.getStudents().stream()
Troppo tardi!

2021-05-11 07:37 UTC, Wabri commented on src/main/java/it/plansoft/classmanager/controller/ClassroomController.java
> +		return c.getStudents().stream()
Faccio un revert :smile:

2021-05-11 07:46 UTC, Wabri commented
Pr riaperta #48